config/routes.rb
IouApp::Application.routes.draw do
  root "user#profile"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/home', to: 'welcome#home'

  get '/transaction/create', to: 'transaction#create'
  post '/transaction/post', to: 'transaction#post'

  get '/iou', to: 'transaction#iou'
  get '/uoi', to: 'transaction#uoi'

  get '/transaction/:id', to: 'transaction#display'
  get '/transaction/delete/:id', to: 'transaction#delete'
  post '/transaction/paidback', to: 'transaction#paidback'
  post '/transaction/reject', to: 'transaction#reject'

  get '/profile', to: 'user#profile'

  get '/welcome/home/:email', to: 'welcome#email'

end

app/controllers/transaction_controller.rb
class TransactionController < ActionController::Base
  layout 'application'
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user! #checks if user is signed in

  def create
    all_users = User.find(current_user.id).friends_registered.to_json
    unless all_users == '[]'
      @all_users = all_users
    end
  end

  def post
    transaction_info = {  'borrower_key' => params["BorrowerKey"],
                          'lender_key' => current_user.id,
                          'amount' => params["Amount"].to_f,
                          'transaction_date' => Time.parse(params["Date"]),
                          'description' => params["Description"] }
    Transaction.newtransaction(transaction_info)

    render :json => {"status" => 200}
  end

  def iou
    @transactions = Transaction.where(:id_b => current_user.id)
  end

  def uoi
    @transactions = Transaction.where(:id_l => current_user.id)
  end

  def delete
    Transaction.deletetransaction(params[:id])
    redirect_to transaction_uoi_url
  end

  def paidback
    if Transaction.paidback(params)
      render :nothing => true, :status => 200, :content_type => 'text/html', :json => {"status" => 200}
    else
      render :nothing => true, :status => 200, :content_type => 'text/html', :json => {"status" => 500}
    end
  end

  def display
    @transaction = Transaction.find(params[:id])
    @loaner = User.find(@transaction.id_l)
    @borrower = User.find(@transaction.id_b)
    @user = current_user
  end

  def reject
    if Transaction.reject(params)
      render :nothing => true, :status => 200, :content_type => 'text/html', :json => {"status" => 200}
    else
      render :nothing => true, :status => 200, :content_type => 'text/html', :json => {"status" => 500}
    end
  end

end

app/views/transaction/create.html.erb
<%= stylesheet_link_tag    "typeahead", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag    "datepicker", media: "all", "data-turbolinks-track" => true %>

<div class="create_transaction_container">
	<div id="selected_users"></div>
	<form id="create_transaction">
		<input class="typeahead" type="text" name="Name" placeholder="Search for people" >
		<!-- HIDDEN FIELDS -->
		<input type="hidden" name="BorrowerKey">
		<!-- END HIDDEN FIELDS -->
		<input type="text" name="Amount" placeholder="Amount (this amount will be split among the selected users)" id="Amount">
		<input type="text" name="Date" class="datepicker" data-date-format="dd-mm-yyyy" placeholder="Date">
		<input type="textbox" name="Description" placeholder="Description">
		<input type="submit" value="Submit" id="submit">
	</form>
</div>

<div id="success" style="display:none">
	Your transaction has been created! <%= link_to 'View transaction?', uoi_path %> or <%= link_to 'create another transaction?', transaction_create_path %>
</div>



<%= javascript_include_tag "bootstrap-datepicker", "data-turbolinks-track" => true %>

<%= javascript_include_tag "handlebars-v1.3.0", "data-turbolinks-track" => true %>
<%= javascript_include_tag "typeahead.bundle", "data-turbolinks-track" => true %>
<%= javascript_include_tag "typeahead.jquery", "data-turbolinks-track" => true %>
<%= javascript_include_tag "typeahead.bundle.min", "data-turbolinks-track" => true %>

<%= javascript_include_tag "jquery.validate", "data-turbolinks-track" => true %>

<script>var all_users = JSON.parse(<%= raw CGI.unescapeHTML(@all_users) %>);</script>
<%= javascript_include_tag "create_transaction", "data-turbolinks-track" => true %>

app/views/transaction/display.html.erb
<%= stylesheet_link_tag    "datepicker", media: "all", "data-turbolinks-track" => true %>

<div class="display_transaction">
	<div class="pic">
		<img src="<%= @borrower.profile_picture %>" class="transaction_pic" />
		<i class="fa fa-2x fa-arrow-right"></i>
		<img src="<%= @loaner.profile_picture %>" class="transaction_pic" />
	</div>
	<div class="header">
		<%= @borrower.fullname %> owes <%= @loaner.fullname %>
		<h1>$<%= sprintf('%.2f', @transaction.amount) %></h1>
	</div>
	<div class="details">
		<table class="details_table">
			<tr>
				<td>Status</td>
				<% if @transaction.paidback %>
					<td>Paidback on <%= Date.parse(@transaction.date_paidback.to_s).strftime("%b %d %Y") %></td>
				<% elsif @transaction.reject %>
					<td>Rejected on <%= Date.parse(@transaction.reject_date.to_s).strftime("%b %d %Y") %></td>
				<% else %>
					<td>Unpaid</td>
				<% end %>
			</tr>
			<% if @transaction.reject %>
			<tr>
				<td>Reject Reason</td>
				<td><%= @transaction.reject_reason %></td>
			</tr>
			<% end %>
			<tr>
				<td>Requested On</td>
				<td><%= Date.parse(@transaction.transaction_date.to_s).strftime("%b %d %Y") %></td>
			</tr>
			<tr>
				<td>Description</td>
				<td><%= @transaction.description %></td>
			</tr>
			<% unless @transaction.paidback %>
				<% unless @user.id == @transaction.id_b %>
					<tr>
						<td>
							<div class="pb-container">
								<input type="text" data-date=<%= @transaction.transaction_date.to_s %> data-id=<%= @transaction.id %> class="pb-date" data-date-format="dd-mm-yyyy" placeholder="Paidback Date">
							</div>
						</td>
						<td>
							<a href="#" data-id=<%= @transaction.id %> class="delete delete-confirm" >Delete</a>
						</td>
					</tr>
				<% end %>
			<% end %>
		</table>
		<% unless @transaction.reject %>
			<% unless @user.id == @transaction.id_l %>
				<a href="#" data-id=<%= @transaction.id %> class="reject_button reject-confirm" >Reject</a>
			<% end %>
		<% end %>
	</div>
	<div class="back" onclick="window.history.back()"><i class="fa fa-caret-left"></i> Go Back</div>
</div>

<%= javascript_include_tag "bootstrap-datepicker" %>
<%= javascript_include_tag "vex.combined.min" %>
<script>
	vex.defaultOptions.className = 'vex-theme-os';
	var now = new Date("<%= @transaction.transaction_date %>");
</script>
<%= stylesheet_link_tag    "vex", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag    "vex-theme-os", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "transactions/display" %>

app/views/transaction/iou.html.erb
<ul class="transaction_container">
	<% @transactions.each do |t| %>
		<% l = User.find(t.id_l) %>
		<li data-id=<%= t.id %>>
			<img src="<%= l.profile_picture %>" class="transaction_pic" />
			<% if t.reject %>
				<div class="icon"><i class="fa fa-2x fa-times reject"></i></div>
				You rejected <b><%= l.fullname %></b> of <div class="money">$<%= sprintf('%.2f', t.amount) %></div>
			<% elsif t.paidback %>
				<div class="icon"><i class="fa fa-2x fa-check check"></i></div>
				You paidback <b><%= l.fullname %></b> <div class="money">$<%= sprintf('%.2f', t.amount) %></div>
			<% else %>
				<div class="icon"><i class="fa fa-2x fa-money owe"></i></div>
				You owe <b><%= l.fullname %></b> <div class="money">$<%= sprintf('%.2f', t.amount) %></div>
			<% end %>
		</li>
	<% end %>
</ul>
<div class="show_transaction">
	<div class="pic">
		<img src="#" class="transaction_pic borrower" />
		<i class="fa fa-2x fa-arrow-right"></i>
		<img src="#" class="transaction_pic lender" />
	</div>
	<div class="header">
		<div class="l_fullname"></div> owes <div class="b_fullname"></div>
		<h1 class="amount"></h1>
	</div>
	<div class="details">
		<table class="details_table">
			<tr>
				<td>Status</td>
				<td class="status"></td>
			</tr>
		</table>
	</div>
</div>
<%= javascript_include_tag "transactions/iou-uoi" %>

app/views/transaction/post.html.erb
hi

app/views/transaction/uoi.html.erb
<div class="row transaction_container">
	<% @transactions.each do |t| %>
		<% b = User.find(t.id_b) %>
		<div class="row each_transaction" data-id=<%= t.id %>>
			<div class="col-xs-3">
				<div align="center">
					<img src="<%= b.profile_picture %>" class="transaction_pic" />
				</div>
			</div>
			<% if t.reject %>
				<div class="icon col-xs-2">
					<i class="fa fa-2x fa-times reject"></i>
				</div>
				<div class="col-xs-7">
					<b><%= b.fullname %></b> rejected <div class="money">$<%= sprintf('%.2f', t.amount) %></div>
				</div>
			<% elsif t.paidback %>
				<div class="icon col-xs-2"><i class="fa fa-2x fa-check check"></i></div>
				<b><%= b.fullname %></b> paidback <div class="money">$<%= sprintf('%.2f', t.amount) %></div>
			<% else %>
				<div class="icon col-xs-2">
					<i class="fa fa-2x fa-money owe"></i>
				</div>
				<div class="col-xs-7">
					<b><%= b.fullname %></b> owes <div class="money">$<%= sprintf('%.2f', t.amount) %></div>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

<%= javascript_include_tag "transactions/iou-uoi" %>